name: mumin
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.6.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.5
  intl: ^0.20.1
  flutter_html: ^3.0.0-beta.2
  wakelock_plus: ^1.2.10
  provider: ^6.1.2
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  geolocator: ^13.0.2
  app_settings: ^5.1.1
  device_info_plus: ^11.2.1
  flutter_native_splash: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.3"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/icon.png
    - assets/images/mumin.png
    - assets/images/suntime.png
    - assets/images/madina.png
    - assets/images/makka.png
    - assets/images/bismillah.png
    - assets/images/mumin/allah.png
    - assets/images/mumin/dua.png
    - assets/images/mumin/hadis.png
    - assets/images/mumin/halal.png
    - assets/images/mumin/istighfer.png
    - assets/images/mumin/kalima.png
    - assets/images/mumin/quran.png
    - assets/images/mumin/ramadan.png
    - assets/images/mumin/ruqyah.png
    - assets/images/mumin/salah.png
    - assets/images/mumin/tasbih.png
    - assets/images/mumin/zakat.png
    - assets/images/mumin/mahram.png
    - assets/images/mahram/male.png
    - assets/images/mahram/female.png
    - assets/images/dua/alhamdulillah.png
    - assets/images/dua/cleaning.png
    - assets/images/dua/dressing.png
    - assets/images/dua/eat.png
    - assets/images/dua/family.png
    - assets/images/dua/hajj.png
    - assets/images/dua/illness.png
    - assets/images/dua/nature.png
    - assets/images/dua/quran_dua.png
    - assets/images/dua/ramadan.png
    - assets/images/dua/ruqiah.png
    - assets/images/dua/salah.png
    - assets/images/dua/shield.png
    - assets/images/dua/sleeping.png
    - assets/images/dua/sociality.png
    - assets/images/dua/suntime_sunset.png
    - assets/images/dua/traveling.png
    - assets/images/dua/wealth.png
    - assets/images/ruqyah/abt_ruqya.png
    - assets/images/ruqyah/do_ruqya.png
    - assets/images/ruqyah/next_step.png
    - assets/images/ruqyah/jin.png
    - assets/images/ruqyah/jadu_tona.png
    - assets/images/ruqyah/bodnozor.png
    - assets/images/ruqyah/jadur_ruqya.png
    - assets/images/ruqyah/sickness_ruqya.png
    - assets/images/ruqyah/raqi.png
    - assets/images/ruqyah/upokoron.png
    - assets/images/ruqyah/hijama.png
    - assets/images/ruqyah/ditox.png
    - assets/images/ruqyah/was_wasa.png
    - assets/images/ruqyah/video.png
    - assets/images/salah/adhan.png
    - assets/images/salah/dua.png
    - assets/images/salah/info.png
    - assets/images/salah/niyat.png
    - assets/images/salah/rakah_break.png
    - assets/images/salah/ruku.png
    - assets/images/salah/sajdah.png
    - assets/images/salah/salam.png
    - assets/images/salah/salah.png
    - assets/images/salah/sana.png
    - assets/images/salah/shower.png
    - assets/images/salah/takber.png
    - assets/images/salah/tasahadud.png
    - assets/images/salah/tayammum.png
    - assets/images/salah/wudu.png
    - assets/data/asmaul_husna.json
    - assets/data/kalimas.json
    - assets/data/hadith.json
    - assets/data/validities.json
    - assets/data/quran/quran_suras.json
    - assets/data/quran/quran.json
    - assets/data/istegfar.json
    - assets/data/dua/dua_category.json
    - assets/data/dua/dua_collection.json
    - assets/data/salah/salatur_category.json
    - assets/data/salah/salatur_topics.json
    - assets/data/salah/salah.json
    - assets/data/salah/salah_topics.json
    - assets/data/mahram.json
    - assets/data/ruqyah/category.json
    - assets/data/ruqyah/sub_category.json
    - assets/data/ruqyah/ruqyah_details.json
    - assets/data/ruqyah/instant_ruqyah.json
    - assets/data/ruqyah/video_cat.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
